services:
  postgres:
    image: postgres:16-alpine
    container_name: projedata-db
    environment:
      POSTGRES_DB: projedata
      POSTGRES_USER: projedata
      POSTGRES_PASSWORD: projedata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
